import type { DatabaseClient, VerifiedServerPrincipal } from "../db/client.ts";
import { DatabaseUnavailableError } from "../db/errors.ts";

export type DashboardGame = Readonly<{ gameId:number; title:string; appId:string|null; playtimeMinutes:number|null; completedAt:string|null; imageUrl:string|null }>;
export type CompletionSuggestion = Readonly<{ game:DashboardGame; estimatedMinutes:number; progressPercent:number; confidence:number }>;
export type DashboardPayload = Readonly<{
  revision:Readonly<{library:string;state:string}>;
  aggregates:Readonly<{ownedGames:number;familyGames:number;completedGames:number;completedPercent:number;totalMinutes:number;unplayedGames:number;pricedGames:number;libraryValueCents:number|null;completedValueCents:number|null;unplayedValueCents:number|null}>;
  trend:Readonly<{daysTracked:number;minutesLast7Days:number;minutesLast30Days:number;dailyGains:readonly {day:string;minutes:number}[]}>;
  mostPlayed:readonly DashboardGame[];recentCompletions:readonly DashboardGame[];completionSuggestions:readonly CompletionSuggestion[];
}>;
type AggregateRow={library_revision:string|number;state_revision:string|number;owned_games:string|number;family_games:string|number;completed_games:string|number;total_minutes:string|number;unplayed_games:string|number};
type GameRow={game_id:number;title:string;steam_app_id:string|number|null;playtime_minutes:number|null;completed_at:string|Date|null;capsule_image_url:string|null;estimated_minutes?:number;progress_percent?:number;confidence?:string|number};

export class DashboardRepository {
  private readonly database:DatabaseClient;
  constructor(database:DatabaseClient){this.database=database;}
  async read(principal:VerifiedServerPrincipal):Promise<DashboardPayload>{
    try{return await this.database.withPrincipal(principal,async tx=>{
      const aggregates=await tx<AggregateRow[]>`with owned as(select lg.game_id,lg.playtime_minutes,gs.completed_at from app.library_games lg join catalog.games g on g.id=lg.game_id left join app.game_state gs on gs.account_id=${principal.accountId} and gs.game_id=lg.game_id where lg.account_id=${principal.accountId} and g.lifecycle_status='active'),family as(select distinct f.game_id from app.family_game_access f join catalog.games g on g.id=f.game_id where f.account_id=${principal.accountId} and g.lifecycle_status='active' and not exists(select 1 from app.library_games lg where lg.account_id=f.account_id and lg.game_id=f.game_id)) select a.library_revision,a.state_revision,(select count(*) from owned) owned_games,(select count(*) from family) family_games,(select count(*) from owned where completed_at is not null) completed_games,coalesce((select sum(playtime_minutes) from owned),0) total_minutes,(select count(*) from owned where playtime_minutes=0) unplayed_games from app.accounts a where a.id=${principal.accountId}`;
      const highlights=await tx<GameRow[]>`select lg.game_id,g.title,g.steam_app_id,lg.playtime_minutes,gs.completed_at,gm.capsule_image_url from app.library_games lg join catalog.games g on g.id=lg.game_id left join app.game_state gs on gs.account_id=${principal.accountId} and gs.game_id=lg.game_id left join catalog.game_metadata gm on gm.game_id=lg.game_id where lg.account_id=${principal.accountId} and g.lifecycle_status='active' order by lg.playtime_minutes desc nulls last,g.normalized_sort_title,lg.game_id limit 5`;
      const completions=await tx<GameRow[]>`select lg.game_id,g.title,g.steam_app_id,lg.playtime_minutes,gs.completed_at,gm.capsule_image_url from app.library_games lg join catalog.games g on g.id=lg.game_id join app.game_state gs on gs.account_id=${principal.accountId} and gs.game_id=lg.game_id left join catalog.game_metadata gm on gm.game_id=lg.game_id where lg.account_id=${principal.accountId} and g.lifecycle_status='active' and gs.completed_at is not null order by gs.completed_at desc,lg.game_id desc limit 8`;
      const suggestions=await tx<GameRow[]>`with candidate as(select lg.game_id,g.title,g.steam_app_id,lg.playtime_minutes,gs.completed_at,gm.capsule_image_url,gs.completion_dismissed_at,gs.completion_dismissed_playtime,gf.duration_kind,round((coalesce(nullif(gf.main_duration_minutes,0),nullif(gf.extras_duration_minutes,0),nullif(gf.completion_duration_minutes,0))+coalesce(nullif(gf.extras_duration_minutes,0),nullif(gf.main_duration_minutes,0),nullif(gf.completion_duration_minutes,0))+coalesce(nullif(gf.completion_duration_minutes,0),nullif(gf.extras_duration_minutes,0),nullif(gf.main_duration_minutes,0)))/3.0)::integer estimated_minutes from app.library_games lg join catalog.games g on g.id=lg.game_id left join app.game_state gs on gs.account_id=${principal.accountId} and gs.game_id=lg.game_id left join catalog.game_metadata gm on gm.game_id=lg.game_id join catalog.game_features gf on gf.game_id=lg.game_id where lg.account_id=${principal.accountId} and g.lifecycle_status='active' and gs.completed_at is null and gf.duration_kind<>'endless') select *,least(100,round(playtime_minutes*100.0/estimated_minutes))::integer progress_percent,case when playtime_minutes<=estimated_minutes*1.5 then 1 when playtime_minutes<=estimated_minutes*2.5 then .8 when playtime_minutes<=estimated_minutes*4 then .6 else .4 end confidence from candidate where estimated_minutes>=120 and playtime_minutes>=estimated_minutes*.75 and (completion_dismissed_at is null or playtime_minutes>=coalesce(completion_dismissed_playtime,0)+greatest(180,coalesce(completion_dismissed_playtime,0)*.25)) order by confidence desc,progress_percent desc,game_id limit 50`;
      const daily=await tx<{day:string|Date;minutes:string|number;ordinal:string|number}[]>`with snapshots as(select activity_day,observed_minutes,lag(observed_minutes) over(order by activity_day) previous from app.playtime_daily where account_id=${principal.accountId} order by activity_day desc limit 31) select activity_day day,greatest(0,observed_minutes-previous) minutes,row_number() over(order by activity_day desc) ordinal from snapshots where previous is not null order by activity_day desc`;
      const row=aggregates[0]??{library_revision:0,state_revision:0,owned_games:0,family_games:0,completed_games:0,total_minutes:0,unplayed_games:0};const owned=Number(row.owned_games),completed=Number(row.completed_games);const gains=daily.map(x=>({day:x.day instanceof Date?x.day.toISOString().slice(0,10):String(x.day),minutes:Number(x.minutes)}));
      return Object.freeze({revision:Object.freeze({library:String(row.library_revision),state:String(row.state_revision)}),aggregates:Object.freeze({ownedGames:owned,familyGames:Number(row.family_games),completedGames:completed,completedPercent:owned?Math.round(completed*100/owned):0,totalMinutes:Number(row.total_minutes),unplayedGames:Number(row.unplayed_games),pricedGames:0,libraryValueCents:null,completedValueCents:null,unplayedValueCents:null}),trend:Object.freeze({daysTracked:daily.length?daily.length+1:0,minutesLast7Days:gains.slice(0,7).reduce((n,x)=>n+x.minutes,0),minutesLast30Days:gains.slice(0,30).reduce((n,x)=>n+x.minutes,0),dailyGains:Object.freeze(gains)}),mostPlayed:Object.freeze(highlights.map(game)),recentCompletions:Object.freeze(completions.map(game)),completionSuggestions:Object.freeze(suggestions.map(x=>Object.freeze({game:game(x),estimatedMinutes:Number(x.estimated_minutes),progressPercent:Number(x.progress_percent),confidence:Number(x.confidence)})))});
    });}catch(error){if(error instanceof DatabaseUnavailableError)throw error;throw new DatabaseUnavailableError();}
  }
}
function game(row:GameRow):DashboardGame{return Object.freeze({gameId:row.game_id,title:row.title,appId:row.steam_app_id===null?null:String(row.steam_app_id),playtimeMinutes:row.playtime_minutes,completedAt:row.completed_at===null?null:row.completed_at instanceof Date?row.completed_at.toISOString():row.completed_at,imageUrl:row.capsule_image_url});}
