begin transaction isolation level repeatable read read only; set local statement_timeout='30s'; set local lock_timeout='2s'; set local timezone='UTC';
select jsonb_build_object(
'source_project_ref','pfvblcopcmairdfeqdep','observed_at_utc',clock_timestamp(),'evidence_kind','read-only conflict aggregates; not export or cutover',
'identity',(select row_to_json(r) from (select count(*) as accounts,count(*) filter(where a.account_type='manual') as manual_accounts,count(*) filter(where a.account_type='manual' and p.id is null) as manual_without_profile,count(*) filter(where a.account_type='steam' and u.id is null) as steam_without_profile,count(*) filter(where u.id is not null and p.id is not null) as both_profile_kinds from public.app_accounts a left join public.app_users u on u.id=a.id left join public.manual_steam_profiles p on p.id=a.id) r),
'visibility',(select row_to_json(r) from (select count(*) as compared_accounts,count(*) filter(where a.steam_library_visible is distinct from u.steam_library_visible) as library_disagreement,count(*) filter(where a.steam_playtime_visible is distinct from u.steam_playtime_visible) as playtime_disagreement,count(*) filter(where a.steam_last_played_visible is distinct from u.steam_last_played_visible) as recency_disagreement,count(*) filter(where a.steam_visibility_checked_at is distinct from u.steam_visibility_checked_at) as checked_time_disagreement from public.app_accounts a join public.app_users u on u.id=a.id) r),
'completions',(select row_to_json(r) from (select count(*) as events,count(*) filter(where ug.id is null and ce.steam_appid is null) as unresolved_game_identity,count(*) filter(where ug.id is not null and ug.user_id<>ce.user_id) as library_account_mismatch,count(*) filter(where ce.game_id is not null and ug.id is null) as deleted_library_reference,count(*) filter(where ce.steam_appid is not null and cg.steam_appid is null) as appid_absent_from_catalogue,count(*) filter(where ce.undone_at<ce.claimed_at) as undo_before_claim from public.completion_events ce left join public.user_games ug on ug.id=ce.game_id left join public.catalog_games cg on cg.steam_appid=ce.steam_appid) r),
'collections',(select row_to_json(r) from (select count(*) as populated_collections,count(*) filter(where total<>positions) as duplicate_position_collections,count(*) filter(where lo<>0 or hi<>total-1) as non_dense_position_collections from (select collection_id,count(*) as total,count(distinct position) as positions,min(position) as lo,max(position) as hi from public.collection_games group by collection_id) c) r),
'family',(select row_to_json(r) from (select count(*) as accounts_with_members,count(*) filter(where members>5) as over_cap_accounts,max(members) as largest_family from (select user_id,count(*) as members from public.user_family_members group by user_id) f) r),
'family_orphans',(select row_to_json(r) from (select count(*) filter(where ug.family_owner_steam_id is not null) as rows_with_lender,count(*) filter(where ug.family_owner_steam_id is not null and m.id is null) as rows_without_member from public.user_games ug left join public.user_family_members m on m.user_id=ug.user_id and m.steam_id=ug.family_owner_steam_id) r),
'session_shapes',(select row_to_json(r) from (select count(*) as steam_sessions,count(*) filter(where token_hash is null or token_hash!~'^[0-9A-Fa-f]{64}$') as invalid_hex,count(*) filter(where expires_at<=created_at) as invalid_expiry from public.sessions) r),
'session_decoded_collisions',(select count(*) from (select lower(token_hash) as digest from public.sessions where token_hash~'^[0-9A-Fa-f]{64}$' intersect select lower(token_hash) from public.manual_profile_sessions where token_hash~'^[0-9A-Fa-f]{64}$') d),
'merges',(select row_to_json(r) from (select count(*) as merge_rows,count(*) filter(where a.id is null) as deleted_source_rows,count(distinct m.source_account_id) filter(where a.id is null) as required_source_tombstones,count(*) filter(where m.merge_mode='promoted' and m.source_account_id<>m.target_account_id) as invalid_promoted_identity from public.account_merges m left join public.app_accounts a on a.id=m.source_account_id) r)
) as audit; commit;
