/** Steam account country list, checked 30 September 2026.
 * Source: https://store.steampowered.com/join/?l=english
 * Includes territories and Kosovo (XK); Steam does not list North Korea.
 * Shared by the menu, pricing API and v2 cache repository.
 */
export const STEAM_STORE_REGIONS = [
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "DE", name: "Germany" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "AF", name: "Afghanistan" },
  { code: "AX", name: "Aland Islands" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BR", name: "Brazil" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CV", name: "Cape Verde" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CX", name: "Christmas Island" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CD", name: "Congo, Democratic Republic of the" },
  { code: "CG", name: "Congo, Republic of the" },
  { code: "CK", name: "Cook Islands" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Cote d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FK", name: "Falkland Islands (Malvinas)" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "TF", name: "French Southern Territories" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HM", name: "Heard and Mc Donald Islands" },
  { code: "VA", name: "Holy See(Vatican City State)" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IM", name: "Isle of Man" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KR", name: "Korea, Republic of" },
  { code: "XK", name: "Kosovo" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Lao People's Democratic Republic" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macau" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia, Federated States of" },
  { code: "MD", name: "Moldova, Republic of" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk Island" },
  { code: "MK", name: "North Macedonia, Republic of" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestinian Territory, Occupied" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PN", name: "Pitcairn" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Reunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russian Federation" },
  { code: "RW", name: "Rwanda" },
  { code: "BL", name: "Saint Barthélemy" },
  { code: "SH", name: "Saint Helena" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "MF", name: "Saint Martin" },
  { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SX", name: "Sint Maarten" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania, United Republic of" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "TR", name: "Türkiye" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "UM", name: "United States Minor Outlying Islands" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Viet Nam" },
  { code: "VG", name: "Virgin Islands, British" },
  { code: "VI", name: "Virgin Islands, U.S." },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "EH", name: "Western Sahara" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
] as const;

const storeCountries = new Set<string>(STEAM_STORE_REGIONS.map(region => region.code));
export function isSteamStoreCountry(value: unknown): value is string {
  return typeof value === "string" && storeCountries.has(value);
}

/** User-facing pricing markets, rather than the 249-country account list.
 * Steam's 37 live currencies and four distinct USD pricing groups:
 * https://partner.steamgames.com/doc/store/pricing/currencies?l=english
 * `code` is a representative store country for the existing pricing API/cache.
 * Regional prices are indicative; the user's own Steam store controls checkout.
 */
export const STEAM_PRICE_MARKETS = [
  { code: "GB", name: "United Kingdom", currency: "GBP", countries: "GB" },
  { code: "US", name: "United States / Global", currency: "USD", countries: "US" },
  { code: "FR", name: "Europe", currency: "EUR", countries: "FR AD AL AT AX BA BE BG CY CZ DE DK EE ES FI FO GG GI GR HR HU IE IM IS IT JE LI LT LU LV MC ME MK MT NL PT RO RS SE SI SK SM VA XK" },
  { code: "CA", name: "Canada", currency: "CAD", countries: "CA" },
  { code: "AU", name: "Australia", currency: "AUD", countries: "AU" },
  { code: "AR", name: "Latin America", currency: "USD", countries: "AR BZ BO EC SV GT GY HN NI PA PY SR VE" },
  { code: "TR", name: "Middle East & North Africa", currency: "USD", countries: "TR BH EG IQ JO LB OM PS YE DZ LY MA TN SD" },
  { code: "PK", name: "South Asia", currency: "USD", countries: "PK BD BT NP LK" },
  { code: "AM", name: "CIS & neighbouring markets", currency: "USD", countries: "AM AZ BY GE KG MD TJ TM UZ" },
  { code: "BR", name: "Brazil", currency: "BRL", countries: "BR" },
  { code: "CL", name: "Chile", currency: "CLP", countries: "CL" },
  { code: "CN", name: "China", currency: "CNY", countries: "CN" },
  { code: "CO", name: "Colombia", currency: "COP", countries: "CO" },
  { code: "CR", name: "Costa Rica", currency: "CRC", countries: "CR" },
  { code: "HK", name: "Hong Kong", currency: "HKD", countries: "HK" },
  { code: "IN", name: "India", currency: "INR", countries: "IN" },
  { code: "ID", name: "Indonesia", currency: "IDR", countries: "ID" },
  { code: "IL", name: "Israel", currency: "ILS", countries: "IL" },
  { code: "JP", name: "Japan", currency: "JPY", countries: "JP" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", countries: "KZ" },
  { code: "KW", name: "Kuwait", currency: "KWD", countries: "KW" },
  { code: "MY", name: "Malaysia", currency: "MYR", countries: "MY" },
  { code: "MX", name: "Mexico", currency: "MXN", countries: "MX" },
  { code: "NZ", name: "New Zealand", currency: "NZD", countries: "NZ" },
  { code: "NO", name: "Norway", currency: "NOK", countries: "NO" },
  { code: "PE", name: "Peru", currency: "PEN", countries: "PE" },
  { code: "PH", name: "Philippines", currency: "PHP", countries: "PH" },
  { code: "PL", name: "Poland", currency: "PLN", countries: "PL" },
  { code: "QA", name: "Qatar", currency: "QAR", countries: "QA" },
  { code: "RU", name: "Russia", currency: "RUB", countries: "RU" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", countries: "SA" },
  { code: "SG", name: "Singapore", currency: "SGD", countries: "SG" },
  { code: "ZA", name: "South Africa", currency: "ZAR", countries: "ZA" },
  { code: "KR", name: "South Korea", currency: "KRW", countries: "KR" },
  { code: "CH", name: "Switzerland", currency: "CHF", countries: "CH" },
  { code: "TW", name: "Taiwan", currency: "TWD", countries: "TW" },
  { code: "TH", name: "Thailand", currency: "THB", countries: "TH" },
  { code: "UA", name: "Ukraine", currency: "UAH", countries: "UA" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", countries: "AE" },
  { code: "UY", name: "Uruguay", currency: "UYU", countries: "UY" },
  { code: "VN", name: "Vietnam", currency: "VND", countries: "VN" },
] as const;

const priceMarketsByCountry = new Map<string, typeof STEAM_PRICE_MARKETS[number]>();
for (const market of STEAM_PRICE_MARKETS) {
  for (const country of market.countries.split(" ")) priceMarketsByCountry.set(country, market);
}

export function steamPriceMarket(country: string) {
  return priceMarketsByCountry.get(country) ?? STEAM_PRICE_MARKETS[1];
}

const priceMarketSearch = new Map(STEAM_PRICE_MARKETS.map(market => [market.code, `${market.name} ${market.currency} ${market.countries} ${STEAM_STORE_REGIONS.filter(region => steamPriceMarket(region.code).code === market.code).map(region => region.name).join(" ")} ${market.code === "GB" ? "UK Britain" : market.code === "US" ? "USA Global" : ""}`.toLowerCase()]));

export function steamPriceMarketSearch(market: typeof STEAM_PRICE_MARKETS[number]) {
  return priceMarketSearch.get(market.code)!;
}

// Rounded recommendation bands near £10, broadened to twice that when needed.
// These are local affordability limits, not live FX quotes. Steam reports all
// prices in hundredths, including JPY, KRW and KWD (not ISO minor-unit scales).
// https://partner.steamgames.com/doc/store/pricing/currencies
const BUDGET_LIMITS: Readonly<Record<string, number>> = {
  AED: 4800, AUD: 2000, BRL: 7000, CAD: 1800, CHF: 1200,
  CLP: 1300000, CNY: 9500, COP: 5500000, CRC: 650000, EUR: 1200,
  GBP: 1000, HKD: 10000, ILS: 4800, IDR: 21000000, INR: 110000,
  JPY: 200000, KRW: 1800000, KWD: 400, KZT: 650000, MXN: 25000,
  MYR: 6000, NOK: 15000, NZD: 2300, PEN: 4800, PHP: 75000,
  PLN: 5000, QAR: 4800, RUB: 120000, SAR: 5000, SGD: 1800,
  THB: 45000, TWD: 43000, UAH: 55000, USD: 1300, UYU: 55000,
  VND: 34000000, ZAR: 25000,
};

export function steamBudgetBand(currency: string | undefined) {
  const first = currency ? BUDGET_LIMITS[currency] : undefined;
  return typeof first !== "number" ? null : { first, fallback: first * 2 };
}
