project_id = "vaultshuffle-v2"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 17

[features.multi_agent_v2]
enabled = true
min_wait_timeout_ms = 1500000
default_wait_timeout_ms = 1500000
max_wait_timeout_ms = 1500000